blueprint:
  name: Light Toggle
  description: Toggles a light.
  domain: automation
  author: Eduard Llull
  input:
    triggers:
      name: Triggers
      description: What will trigger the light toggle.
      selector:
        trigger:

    lights:
      name: Lights
      description: Lights to toggle.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

    transition:
      name: Transition
      description: Duration it takes to get to next state.
      default:
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: seconds

    color_temp_kelvin:
      name: Color temperature
      description: Color temperature in Kelvin.
      default:
      selector:
        color_temp:
          unit: kelvin
          min: 2000
          max: 8000

    brightness_pct:
      name: Brightness
      description: Number indicating the percentage of full brightness, where 0 turns the light off, 1 is the minimum brightness, and 100 is the maximum brightness.
      default:
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

mode: single
max_exceeded: silent

triggers: !input triggers

actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: !input lights
    data:
      brightness_pct: !input brightness_pct
      color_temp_kelvin: !input color_temp_kelvin
      transition: !input transition
