blueprint:
  name: Save Light Last Attributes
  description: Saves the attributes of a light every time they change.
  domain: automation
  input:
    track_light:
      name: Light
      description: The light to track.
      selector:
        entity:
          filter:
            - domain: light
    target_input_text:
      name: Text Input
      description: Text input to save the attributes to.
      selector:
        target:
          entity:
              - domain: input_text

triggers:
  - trigger: state
    entity_id: !input track_light

conditions:
  - condition: template
    value_template: "{{ trigger.to_state.state == 'on' }}"

actions:
  - action: input_text.set_value
    metadata: {}
    target: !input target_input_text
    data:
      value: |
        {{
          {
            "brightness": trigger.to_state.attributes.brightness,
            "color_temp_kelvin": trigger.to_state.attributes.color_temp_kelvin,
          } | to_json
        }}

mode: restart
