blueprint:
  name: Light Toggle
  description: Toggles a light.
  domain: automation
  author: Eduard Llull
  input:
    triggers:
      name: Triggers
      description: What will trigger the light toggle.
      selector:
        trigger:

    lights:
      name: Lights
      description: Lights to toggle.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

    has_transition:
      name: Transition
      description: Duration it takes to get to next state.
      default: false
      selector:
        boolean:

    transition:
      default:
      selector:
        number:
          min: 0
          max: 300
          step: 1
          unit_of_measurement: seconds

mode: single
max_exceeded: silent

triggers: !input triggers

actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: !input lights
    data:
      brightness_pct: 100
      color_temp_kelvin: 2702
      transition: !input transition
