blueprint:
  name: Light Toggle
  description: Toggles a light.
  domain: automation
  author: Eduard Llull
  input:
    triggers:
      name: Triggers
      description: What will trigger the light toggle.
      selector:
        trigger:

    lights:
      name: Lights
      description: Lights to toggle.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

    lights_controls:
      name: Light Control
      icon: mdi:lightbulb-on-outline
      collapsed: true
      input:
        include_light_control:
          name: Light Control Options (Optional)
          description: >
            Select if you would like to use brightness or transition.
            These settings will only affect a 'light' entity that supports each selected option.
          default: []
          selector:
            select:
              multiple: true
              options:
                - label: Use Transition
                  value: "use_transition"
                - label: Use Brightness
                  value: "use_brightness"
                - label: Use Color Temperature
                  value: "use_color_temerature"

        transition:
          name: Transition
          description: Duration it takes to get to next state.
          default: 1
          selector:
            number:
              min: 0
              max: 300
              step: 0.5
              unit_of_measurement: seconds
    
        brightness_pct:
          name: Brightness
          description: Number indicating the percentage of full brightness, where 0 turns the light off, 1 is the minimum brightness, and 100 is the maximum brightness.
          default: 100
          selector:
            number:
              min: 0
              max: 100
              step: 1
              unit_of_measurement: "%"
              mode: slider

        color_temp_kelvin:
          name: Color temperature
          description: Color temperature in Kelvin.
          default:
          selector:
            color_temp:
              unit: kelvin
              min: 2000
              max: 8000
    

mode: restart

variables:
  include_light_control: !input include_light_control
  transition: !input transition
  brightness_pct: !input brightness_pct
  color_temp_kelvin: !input color_temp_kelvin

# Light data
  light_data: >-
    {% set light = namespace(data={}) %}
        {% if 'use_transition' in include_light_control %}
      {% set light.data = dict(light.data, **{ 'transition': transition }) %}
    {% endif %}
    {% if 'use_brightness' in include_light_control %}
      {% set light.data = dict(light.data, **{ 'brightness_pct': brightness_pct }) %}
    {% endif %}
    {% if 'use_color_temerature' in include_light_control %}
      {% set light.data = dict(light.data, **{ 'color_temp_kelvin': color_temp_kelvin }) %}
    {% endif %}
    {{ light.data }}

triggers: !input triggers

actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: !input lights
    data: "{{ light_data }}"
